apiVersion: v1
kind: Namespace
metadata:
  name: stunner-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stunner-gateway
  namespace: stunner-gateway
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stunner-gateway
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  - gateways
  - httproutes
  verbs:
  - list
  - watch
- apiGroups:
  - stunner.l7mp.io
  resources:
  - gatewayconfigs
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes/status
  verbs:
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stunner-gateway
subjects:
- kind: ServiceAccount
  name: stunner-gateway
  namespace: stunner-gateway
roleRef:
  kind: ClusterRole
  name: stunner-gateway
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stunner-gateway
  namespace: stunner-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stunner-gateway
  template:
    metadata:
      labels:
        app: stunner-gateway
    spec:
      shareProcessNamespace: true
      serviceAccountName: stunner-gateway
      volumes:
      - name: stunner-config
        emptyDir: { }
      initContainers:
      - image: busybox:1.34 # FIXME(pleshakov): use gateway container to init the Config with proper main config
        name: stunner-config-initializer
        command: [ 'sh', '-c', 'cp /app/stunner.conf /etc/stunner/stunner.conf' ]
        volumeMounts:
        - name: stunner-config
          mountPath: /etc/stunner
      containers:
      - image: stunner-kubernetes-gateway:0.0.1
        imagePullPolicy: IfNotPresent
        name: stunner-gateway
        volumeMounts:
        - name: stunner-config
          mountPath: /etc/stunner
        args:
        - --gateway-ctlr-name=stunner.l7mp.io/gateway
      - image: l7mp/stunnerd
        imagePullPolicy: IfNotPresent
        name: stunner
        volumeMounts:
        - name: stunner-config
          mountPath: /etc/stunner
