apiVersion: v1
kind: Service
metadata:
  name: stunner-gateway
  namespace: stunner-gateway
spec:
  type: NodePort 
  ports:
  - port: 3478
    targetPort: 3478
    protocol: UDP
    name: udp
  selector:
    app: stunner-gateway
